[general]
static=yes
writeprotect=yes

[default]
exten => _X!,1,Hangup(21)

[ai-local-test]
exten => 700,1,Answer()
 same => n,Set(TIMEOUT(absolute)=600)
 same => n,Set(AI_UUID=${FILTER(0-9a-f\-,${SHELL(cat /proc/sys/kernel/random/uuid)})})
 same => n,AudioSocket(${AI_UUID},127.0.0.1:9019)
 same => n,Hangup()

[from-voipunify]
exten => 300405272,1,Goto(ai-local-test,700,1)
exten => 351300405272,1,Goto(ai-local-test,700,1)
exten => +351300405272,1,Goto(ai-local-test,700,1)
exten => airbagstst,1,Goto(ai-local-test,700,1)
